import PDFDocument from 'pdfkit';
import crypto from 'crypto';

export interface AuditTrailPdfParams {
  event: Record<string, unknown>;
  auditEvents: Record<string, unknown>[];
  ledgerEntries: Record<string, unknown>[];
  complianceScore?: { score: number; band: string };
}

export interface RulingPdfParams {
  review: Record<string, unknown>;
  standards: { code: string; title: string }[];
}

function sha256(content: string): string {
  return crypto.createHash('sha256').update(content).digest('hex');
}

export function generateAuditTrailPdf(params: AuditTrailPdfParams): Buffer {
  const doc = new PDFDocument({ margin: 50 });
  const buffers: Buffer[] = [];
  doc.on('data', (b: Buffer) => buffers.push(b));

  const content: string[] = [];

  // Header
  doc.fontSize(20).font('Helvetica-Bold').text('ICOS — Audit Trail', { align: 'center' });
  doc.fontSize(10).font('Helvetica').text(`Generated: ${new Date().toISOString()}`, { align: 'center' });
  doc.moveDown();

  // Event details
  doc.fontSize(14).font('Helvetica-Bold').text('Event Details');
  doc.fontSize(10).font('Helvetica');
  const eventFields = ['event_id', 'event_type', 'linked_contract_id', 'asset_reference', 'quantity', 'unit', 'approval_state'];
  for (const f of eventFields) {
    if (params.event[f] !== undefined) {
      const line = `${f}: ${params.event[f]}`;
      doc.text(line);
      content.push(line);
    }
  }
  doc.moveDown();

  // Approval timeline
  doc.fontSize(14).font('Helvetica-Bold').text('Approval Timeline');
  doc.fontSize(10).font('Helvetica');
  for (const ae of params.auditEvents) {
    const line = `[${ae.timestamp}] ${ae.reviewer_role} → ${ae.new_state}: ${ae.decision_reason}`;
    doc.text(line);
    content.push(line);
  }
  doc.moveDown();

  // Ledger entries
  if (params.ledgerEntries.length > 0) {
    doc.fontSize(14).font('Helvetica-Bold').text('Ledger Entries');
    doc.fontSize(10).font('Helvetica');
    for (const le of params.ledgerEntries) {
      const line = `DR ${le.debit_account}  CR ${le.credit_account}  ${le.amount} ${le.currency}`;
      doc.text(line);
      content.push(line);
    }
    doc.moveDown();
  }

  // Compliance score
  if (params.complianceScore) {
    doc.fontSize(14).font('Helvetica-Bold').text('Compliance');
    doc.fontSize(10).font('Helvetica').text(`Score: ${params.complianceScore.score} — ${params.complianceScore.band}`);
    content.push(`Score: ${params.complianceScore.score} — ${params.complianceScore.band}`);
    doc.moveDown();
  }

  // Footer with hash
  const hash = sha256(content.join('\n'));
  doc.fontSize(8).font('Helvetica').text(`Integrity: SHA-256 ${hash}`, { align: 'center' });
  doc.text('Generated by ICOS — Islamic Commercial Operating System', { align: 'center' });

  doc.end();
  return Buffer.concat(buffers);
}

export function generateRulingPdf(params: RulingPdfParams): Buffer {
  const doc = new PDFDocument({ margin: 50 });
  const buffers: Buffer[] = [];
  doc.on('data', (b: Buffer) => buffers.push(b));

  const content: string[] = [];

  // Header
  doc.fontSize(20).font('Helvetica-Bold').text('ICOS — Shariah Review Record', { align: 'center' });
  doc.fontSize(10).font('Helvetica').text(`Generated: ${new Date().toISOString()}`, { align: 'center' });
  doc.moveDown();

  // Review details
  doc.fontSize(14).font('Helvetica-Bold').text('Review Reference');
  doc.fontSize(10).font('Helvetica');
  for (const f of ['review_id', 'related_contract_id', 'reviewer_id', 'timestamp']) {
    if (params.review[f]) {
      const line = `${f}: ${params.review[f]}`;
      doc.text(line); content.push(line);
    }
  }
  doc.moveDown();

  // Legal reasoning
  doc.fontSize(14).font('Helvetica-Bold').text('Legal Reasoning');
  const reasoning = String(params.review.legal_reasoning ?? '(not yet applied)');
  doc.fontSize(10).font('Helvetica').text(reasoning);
  content.push(reasoning);
  doc.moveDown();

  // Cited standards
  if (params.standards.length > 0) {
    doc.fontSize(14).font('Helvetica-Bold').text('Cited AAOIFI Standards');
    doc.fontSize(10).font('Helvetica');
    for (const s of params.standards) {
      const line = `${s.code}: ${s.title}`;
      doc.text(line); content.push(line);
    }
    doc.moveDown();
  }

  // Ruling
  doc.fontSize(14).font('Helvetica-Bold').text('Ruling');
  doc.fontSize(10).font('Helvetica');
  for (const f of ['ruling_type', 'ruling_confidence', 'digital_signature']) {
    if (params.review[f] !== undefined) {
      const line = `${f}: ${params.review[f]}`;
      doc.text(line); content.push(line);
    }
  }

  doc.moveDown();
  const hash = sha256(content.join('\n'));
  doc.fontSize(8).font('Helvetica').text(`Integrity: SHA-256 ${hash}`, { align: 'center' });
  doc.text('Generated by ICOS — Islamic Commercial Operating System', { align: 'center' });

  doc.end();
  return Buffer.concat(buffers);
}

export interface LedgerReconciliationPdfParams {
  entries: Record<string, unknown>[];
  summary: {
    total_debits: number;
    total_credits: number;
    entry_count: number;
    balanced: boolean;
    imbalance: number;
  };
  since: string | undefined;
  until: string | undefined;
  generatedBy: string;
  generatedAt: string;
}

export function generateLedgerReconciliationPdf(params: LedgerReconciliationPdfParams): Buffer {
  const { entries, summary, since, until, generatedBy, generatedAt } = params;

  // Hash canonical payload BEFORE building the PDF — avoids circular self-hashing
  const canonicalPayload = JSON.stringify({
    summary,
    since,
    until,
    generatedBy,
    generatedAt,
    entry_ids: entries.map(e => e.entry_id),
  });
  const footerHash = sha256(canonicalPayload);

  const doc = new PDFDocument({ margin: 50 });
  const buffers: Buffer[] = [];
  doc.on('data', (b: Buffer) => buffers.push(b));

  // Header
  doc.fontSize(20).font('Helvetica-Bold').text('ICOS Ledger Reconciliation Report', { align: 'center' });
  doc.fontSize(10).font('Helvetica');
  doc.text(`Period: ${since ?? 'beginning'} — ${until ?? 'now'}`, { align: 'center' });
  doc.text(`Generated by: ${generatedBy}  |  ${generatedAt}`, { align: 'center' });
  doc.moveDown();

  // Section 1: Summary
  doc.fontSize(14).font('Helvetica-Bold').text('Section 1: Summary');
  doc.fontSize(10).font('Helvetica');
  doc.text(`Total entries:  ${summary.entry_count}`);
  doc.text(`Total debits:   ${summary.total_debits.toFixed(2)}`);
  doc.text(`Total credits:  ${summary.total_credits.toFixed(2)}`);
  doc.text(`Imbalance:      ${summary.imbalance.toFixed(2)}`);
  doc.text(`Status:         ${summary.balanced ? 'BALANCED' : 'IMBALANCED'}`);
  doc.moveDown();

  // Section 2: Breakdown by subledger type
  const bySubledger = new Map<string, { count: number; total: number }>();
  for (const e of entries) {
    const key = String(e.debit_account ?? 'unknown');
    const prev = bySubledger.get(key) ?? { count: 0, total: 0 };
    bySubledger.set(key, { count: prev.count + 1, total: prev.total + Number(e.amount ?? 0) });
  }
  doc.fontSize(14).font('Helvetica-Bold').text('Section 2: Breakdown by Subledger Type');
  doc.fontSize(10).font('Helvetica');
  for (const [subledger, stats] of bySubledger) {
    doc.text(`${subledger}: ${stats.count} entries, total ${stats.total.toFixed(2)}`);
  }
  doc.moveDown();

  // Section 3: Integrity audit
  const validCount = entries.filter(e => e.integrity_verified === true).length;
  const invalidCount = entries.filter(e => e.integrity_verified === false).length;
  const tamperedEntries = entries.filter(e => e.integrity_verified === false);
  doc.fontSize(14).font('Helvetica-Bold').text('Section 3: Integrity Audit');
  doc.fontSize(10).font('Helvetica');
  doc.text(`Valid hash:   ${validCount}`);
  doc.text(`Invalid hash: ${invalidCount}`);
  if (tamperedEntries.length > 0) {
    doc.moveDown();
    doc.text('Tampered entries:');
    for (const e of tamperedEntries) {
      doc.text(`  ${e.entry_id} — contract ${e.linked_contract_id} — ${e.timestamp}`);
    }
  }
  doc.moveDown();

  // Section 4: Entry list (only if ≤ 200 entries)
  doc.fontSize(14).font('Helvetica-Bold').text('Section 4: Ledger Entries');
  doc.fontSize(10).font('Helvetica');
  if (entries.length > 200) {
    doc.text(`${entries.length} entries — list omitted (exceeds 200 entry limit)`);
  } else {
    for (const e of entries) {
      const iv = e.integrity_verified === true ? 'OK' : 'TAMPERED';
      doc.text(
        `${e.timestamp}  ${e.linked_contract_id}  D:${e.debit_account}  C:${e.credit_account}  ` +
        `${e.amount} ${e.currency}  [${iv}]`,
        { lineBreak: true }
      );
    }
  }
  doc.moveDown();

  // Footer with canonical payload hash
  doc.fontSize(8).font('Helvetica').text(`Integrity: SHA-256 ${footerHash}`, { align: 'center' });
  doc.text('Generated by ICOS — Islamic Commercial Operating System', { align: 'center' });

  doc.end();
  return Buffer.concat(buffers);
}
