import PDFDocument from 'pdfkit';
import crypto from 'crypto';

export interface AuditTrailPdfParams {
  event: Record<string, unknown>;
  auditEvents: Record<string, unknown>[];
  ledgerEntries: Record<string, unknown>[];
  complianceScore?: { score: number; band: string };
}

export interface RulingPdfParams {
  review: Record<string, unknown>;
  standards: { code: string; title: string }[];
}

function sha256(content: string): string {
  return crypto.createHash('sha256').update(content).digest('hex');
}

export function generateAuditTrailPdf(params: AuditTrailPdfParams): Buffer {
  const doc = new PDFDocument({ margin: 50 });
  const buffers: Buffer[] = [];
  doc.on('data', (b: Buffer) => buffers.push(b));

  const content: string[] = [];

  // Header
  doc.fontSize(20).font('Helvetica-Bold').text('ICOS — Audit Trail', { align: 'center' });
  doc.fontSize(10).font('Helvetica').text(`Generated: ${new Date().toISOString()}`, { align: 'center' });
  doc.moveDown();

  // Event details
  doc.fontSize(14).font('Helvetica-Bold').text('Event Details');
  doc.fontSize(10).font('Helvetica');
  const eventFields = ['event_id', 'event_type', 'linked_contract_id', 'asset_reference', 'quantity', 'unit', 'approval_state'];
  for (const f of eventFields) {
    if (params.event[f] !== undefined) {
      const line = `${f}: ${params.event[f]}`;
      doc.text(line);
      content.push(line);
    }
  }
  doc.moveDown();

  // Approval timeline
  doc.fontSize(14).font('Helvetica-Bold').text('Approval Timeline');
  doc.fontSize(10).font('Helvetica');
  for (const ae of params.auditEvents) {
    const line = `[${ae.timestamp}] ${ae.reviewer_role} → ${ae.new_state}: ${ae.decision_reason}`;
    doc.text(line);
    content.push(line);
  }
  doc.moveDown();

  // Ledger entries
  if (params.ledgerEntries.length > 0) {
    doc.fontSize(14).font('Helvetica-Bold').text('Ledger Entries');
    doc.fontSize(10).font('Helvetica');
    for (const le of params.ledgerEntries) {
      const line = `DR ${le.debit_account}  CR ${le.credit_account}  ${le.amount} ${le.currency}`;
      doc.text(line);
      content.push(line);
    }
    doc.moveDown();
  }

  // Compliance score
  if (params.complianceScore) {
    doc.fontSize(14).font('Helvetica-Bold').text('Compliance');
    doc.fontSize(10).font('Helvetica').text(`Score: ${params.complianceScore.score} — ${params.complianceScore.band}`);
    content.push(`Score: ${params.complianceScore.score} — ${params.complianceScore.band}`);
    doc.moveDown();
  }

  // Footer with hash
  const hash = sha256(content.join('\n'));
  doc.fontSize(8).font('Helvetica').text(`Integrity: SHA-256 ${hash}`, { align: 'center' });
  doc.text('Generated by ICOS — Islamic Commercial Operating System', { align: 'center' });

  doc.end();
  return Buffer.concat(buffers);
}

export function generateRulingPdf(params: RulingPdfParams): Buffer {
  const doc = new PDFDocument({ margin: 50 });
  const buffers: Buffer[] = [];
  doc.on('data', (b: Buffer) => buffers.push(b));

  const content: string[] = [];

  // Header
  doc.fontSize(20).font('Helvetica-Bold').text('ICOS — Shariah Review Record', { align: 'center' });
  doc.fontSize(10).font('Helvetica').text(`Generated: ${new Date().toISOString()}`, { align: 'center' });
  doc.moveDown();

  // Review details
  doc.fontSize(14).font('Helvetica-Bold').text('Review Reference');
  doc.fontSize(10).font('Helvetica');
  for (const f of ['review_id', 'related_contract_id', 'reviewer_id', 'timestamp']) {
    if (params.review[f]) {
      const line = `${f}: ${params.review[f]}`;
      doc.text(line); content.push(line);
    }
  }
  doc.moveDown();

  // Legal reasoning
  doc.fontSize(14).font('Helvetica-Bold').text('Legal Reasoning');
  const reasoning = String(params.review.legal_reasoning ?? '(not yet applied)');
  doc.fontSize(10).font('Helvetica').text(reasoning);
  content.push(reasoning);
  doc.moveDown();

  // Cited standards
  if (params.standards.length > 0) {
    doc.fontSize(14).font('Helvetica-Bold').text('Cited AAOIFI Standards');
    doc.fontSize(10).font('Helvetica');
    for (const s of params.standards) {
      const line = `${s.code}: ${s.title}`;
      doc.text(line); content.push(line);
    }
    doc.moveDown();
  }

  // Ruling
  doc.fontSize(14).font('Helvetica-Bold').text('Ruling');
  doc.fontSize(10).font('Helvetica');
  for (const f of ['ruling_type', 'ruling_confidence', 'digital_signature']) {
    if (params.review[f] !== undefined) {
      const line = `${f}: ${params.review[f]}`;
      doc.text(line); content.push(line);
    }
  }

  doc.moveDown();
  const hash = sha256(content.join('\n'));
  doc.fontSize(8).font('Helvetica').text(`Integrity: SHA-256 ${hash}`, { align: 'center' });
  doc.text('Generated by ICOS — Islamic Commercial Operating System', { align: 'center' });

  doc.end();
  return Buffer.concat(buffers);
}
